export const END_REASON_OPTIONS = [
  { value: '', label: 'Select End Reason' },
  { value: '-7', label: 'CallerHangup' },
  { value: '-8', label: 'CalleeHangup' },
  { value: '-9', label: 'IllegalCall' },
  { value: '-21', label: 'CalleeOffline' },
  { value: '-31', label: 'UnRegistered' },
  { value: '-34', label: 'ProcessTimeout' },
  { value: '-39', label: 'UserBusy' },
  { value: '-43', label: 'NoAnswer' },
  { value: '-69', label: 'NoAvailableRoute' },
  { value: '400', label: 'Bad Request' },
  { value: '403', label: 'Forbidden' },
  { value: '404', label: 'Not Found' },
  { value: '408', label: 'Request Timeout' },
  { value: '480', label: 'Temporary Unavailable' },
  { value: '484', label: 'Address Incomplete' },
  { value: '481', label: 'Call/Transaction Does not Exist' },
  { value: '487', label: 'Request Terminated' },
  { value: '488', label: 'Not Acceptable Here' },
  { value: '500', label: 'Internal Server Error' },
  { value: '501', label: 'Not Implemented' },
  { value: '502', label: 'Bad Gateway' },
  { value: '504', label: 'Server Time-out' },
  { value: '503', label: 'Service Unavailable' },
  { value: '603', label: 'Decline' },
  { value: '604', label: 'Doesnt Exist Anywhere' },
  { value: '607', label: 'Unwanted' },
]
