export interface ECdrResponse {
  data: ECdr[]
  limit: number
  page: number
  total: number
  total_pages: number
  asr: number
}
export interface ECdr {
  ID: number
  Callere164: string
  Calleraccesse164: string
  Calleee164: string
  Calleeaccesse164: string
  CallerIP: string
  Callergatewayh323id: string
  Callerproductid: string
  Callertogatewaye164: string
  CalleeIP: string
  Calleegatewayh323id: string
  Calleeproductid: string
  Calleetogatewaye164: string
  Billingmode: number
  Calllevel: number
  Agentfeetime: number
  Starttime: number
  Stoptime: number
  Pdd: number
  Holdtime: number
  Feeprefix: string
  Feetime: number
  Fee: number
  Suitefee: number
  Suitefeetime: number
  Incomefee: number
  Customeraccount: string
  Customername: string
  Agentfeeprefix: string
  Agentfee: number
  Agentsuitefee: number
  Agentsuitefeetime: number
  Agentaccount: string
  Agentname: string
  Flowno: number
  Softswitchdn: string
  Enddirection: number
  Endreason: number
  Calleebilling: number
  Cdrlevel: number
  SubcdrID: number
}
